---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machinedeployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vpsieclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vpsiemachinetemplates
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - optimization.vpsie.com
  resources:
  - scalingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.vpsie.com
  resources:
  - scalingpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - optimization.vpsie.com
  resources:
  - scalingpolicies/status
  verbs:
  - get
  - patch
  - update
